/*
 * Minimal generated configuration for Allegro 4 on Linux/X11.
 * This matches the Docker/Linux target used by the project.
 */

#define ALLEGRO_COLOR8
#define ALLEGRO_COLOR16
#define ALLEGRO_COLOR24
#define ALLEGRO_COLOR32

#define ALLEGRO_HAVE_DIRENT_H
#define ALLEGRO_HAVE_INTTYPES_H
#define ALLEGRO_HAVE_LINUX_INPUT_H
#define ALLEGRO_HAVE_LINUX_JOYSTICK_H
#define ALLEGRO_HAVE_STDINT_H
#define ALLEGRO_HAVE_SYS_STAT_H
#define ALLEGRO_HAVE_SYS_TIME_H
#define ALLEGRO_HAVE_SYS_UTSNAME_H

#define ALLEGRO_HAVE_MEMCMP
#define ALLEGRO_HAVE_MKSTEMP
#define ALLEGRO_HAVE_MMAP
#define ALLEGRO_HAVE_MPROTECT
#define ALLEGRO_HAVE_POSIX_MONOTONIC_CLOCK
#define ALLEGRO_HAVE_SCHED_YIELD
#define ALLEGRO_HAVE_SYSCONF

#define ALLEGRO_LITTLE_ENDIAN
#define ALLEGRO_NO_ASM
#define ALLEGRO_HAVE_LIBPTHREAD
#define ALLEGRO_USE_CONSTRUCTOR
#define ALLEGRO_WITH_XWINDOWS

#define ALLEGRO_LINUX

#define RETSIGTYPE void
