#ifndef CONFIG_JEU_H
#define CONFIG_JEU_H

enum {
    VALEUR_NULLE = 0,
    VALEUR_UNITAIRE = 1,
    VALEUR_DOUBLE = 2,
    VALEUR_TRIPLE = 3,
    VALEUR_QUADRUPLE = 4,
    VALEUR_QUINTUPLE = 5,
    VALEUR_MILLISECONDES_SECONDE = 1000
};

enum {
    FAUX = VALEUR_NULLE,
    VRAI = VALEUR_UNITAIRE,
    RETOUR_PROGRAMME_OK = VALEUR_NULLE,
    RETOUR_PROGRAMME_ERREUR = VALEUR_UNITAIRE,
    INDEX_PREMIER = VALEUR_NULLE,
    INDEX_SUIVANT = VALEUR_UNITAIRE,
    INDEX_INVALIDE = -1,
    COULEUR_TRANSPARENTE_TEXTE = INDEX_INVALIDE,
    CHAINE_DEBUT = VALEUR_NULLE,
    CARACTERE_FIN_CHAINE = '\0'
};

enum {
    PARAM_SELECTION_RETOUR_SIMPLE = INDEX_SUIVANT
};

enum {
    PROFONDEUR_COULEUR_JEU = 32,
    DUREE_UNE_SECONDE_MS = VALEUR_MILLISECONDES_SECONDE,
    DUREE_UNE_IMAGE_MS = 16,
    DUREE_IMAGE_LOGIQUE_MS = DUREE_UNE_IMAGE_MS,
    VALEUR_DECOMPTE_DEPART = VALEUR_TRIPLE,
    PREMIER_NIVEAU_JEU = VALEUR_UNITAIRE,
    NIVEAU_MAXIMUM_JEU = VALEUR_QUINTUPLE,
    DUREE_NIVEAU_SECONDES = 180,
    ARRONDI_CHRONO_MS = 999,
    DUREE_AURA_ARDENTE_MS = 5000,
    VIE_MAX_BOSS_VOL_DE_MORT = NIVEAU_MAXIMUM_JEU,
    TAILLE_PSEUDO_MAX = 32,
    NOMBRE_FONDS_NIVEAUX = NIVEAU_MAXIMUM_JEU,
    CAPACITE_BULLES_INITIALE = VALEUR_QUADRUPLE,
    FACTEUR_CAPACITE_BULLES = VALEUR_DOUBLE,
    POINTS_BOSS_TOUCHE = 120,
    POINTS_BONUS_CHAPEAU = 250,
    SCORE_BULLE_TRES_GRANDE = 40,
    SCORE_BULLE_GRANDE = 70,
    SCORE_BULLE_MOYENNE = 110,
    SCORE_BULLE_PETITE = 160,
    BONUS_SCORE_VIF_DOR = 140,
    BONUS_SCORE_VOL_DE_MORT = 220,
    DUREE_EXPLOSION_IMAGES = 18
};

enum {
    DIVISEUR_HAUTEUR_SOL = 6,
    DIVISEUR_VITESSE_JOUEUR = 640,
    DIVISEUR_LARGEUR_PROJECTILE = 160,
    DIVISEUR_HAUTEUR_PROJECTILE = 36,
    DIVISEUR_VITESSE_PROJECTILE = 90,
    DIVISEUR_CENTRE = VALEUR_DOUBLE,
    DIVISEUR_TIERS = VALEUR_TRIPLE,
    DIVISEUR_QUART = VALEUR_QUADRUPLE,
    DIVISEUR_CINQUIEME = VALEUR_QUINTUPLE,
    DIVISEUR_SIXIEME = DIVISEUR_HAUTEUR_SOL,
    DIVISEUR_SEPTIEME = 7,
    DIVISEUR_DIXIEME = 10,
    DIVISEUR_TREIZIEME = 13,
    DIVISEUR_QUATORZIEME = 14,
    DIVISEUR_DIX_HUITIEME = DUREE_EXPLOSION_IMAGES,
    DIVISEUR_VINGT_QUATRIEME = 24,
    DIVISEUR_TRENTE_CINQUIEME = 35,
    DIVISEUR_TRENTE_SIXIEME = DIVISEUR_HAUTEUR_PROJECTILE,
    DIVISEUR_QUARANTIEME = 40,
    DIVISEUR_QUARANTE_CINQUIEME = 45,
    DIVISEUR_SOIXANTE_DIXIEME = 70,
    DIVISEUR_QUATRE_VINGT_DIXIEME = DIVISEUR_VITESSE_PROJECTILE,
    DIVISEUR_DEUX_CENT_CINQUANTE_SIXIEME = 256,
    DIVISEUR_TROIS_CENT_QUARANTE_ET_UNIEME = 341
};

enum {
    NUMERATEUR_REDIMENSION_RELATIVE = VALEUR_UNITAIRE,
    INDEX_FOND_NIVEAU_1 = INDEX_PREMIER,
    INDEX_FOND_NIVEAU_2 = INDEX_SUIVANT,
    INDEX_FOND_NIVEAU_3 = VALEUR_DOUBLE,
    INDEX_FOND_NIVEAU_4 = VALEUR_TRIPLE,
    INDEX_FOND_NIVEAU_5 = VALEUR_QUADRUPLE,
    NOMBRE_OPTIONS_MENU_DEPART = NIVEAU_MAXIMUM_JEU,
    NOMBRE_SLOTS_SAUVEGARDE = VALEUR_TRIPLE,
    TAILLE_PSEUDO_AFFICHE = 8,
    SEUIL_TRANSPARENCE_MAGENTA_R = 220,
    SEUIL_TRANSPARENCE_MAGENTA_G = 80,
    SEUIL_TRANSPARENCE_MAGENTA_B = SEUIL_TRANSPARENCE_MAGENTA_R
};

enum {
    DIVISEUR_REDIMENSION_JOUEUR = 25,
    DIVISEUR_REDIMENSION_TIR = 26,
    DIVISEUR_REDIMENSION_FEU = DIVISEUR_REDIMENSION_JOUEUR,
    DIVISEUR_REDIMENSION_CHAPEAU = 30,
    DIVISEUR_REDIMENSION_EXPLOSION = DUREE_EXPLOSION_IMAGES,
    DIVISEUR_REDIMENSION_BULLE_TRES_GRANDE = TAILLE_PSEUDO_AFFICHE,
    DIVISEUR_REDIMENSION_BULLE_GRANDE = 11,
    DIVISEUR_REDIMENSION_BULLE_MOYENNE = 15,
    DIVISEUR_REDIMENSION_BULLE_PETITE = 22
};

enum {
    DIVISEUR_GRAVITE_TRES_GRANDE = 30000,
    DIVISEUR_GRAVITE_GRANDE = DIVISEUR_GRAVITE_TRES_GRANDE,
    DIVISEUR_GRAVITE_MOYENNE = 34000,
    DIVISEUR_GRAVITE_PETITE = 36500,
    DIVISEUR_REBOND_TRES_GRANDE = 190,
    DIVISEUR_REBOND_GRANDE = 205,
    DIVISEUR_REBOND_MOYENNE = 228,
    DIVISEUR_REBOND_PETITE = DIVISEUR_REBOND_GRANDE,
    DIVISEUR_VITESSE_ENFANT_TRES_GRANDE = 8500,
    DIVISEUR_VITESSE_ENFANT_GRANDE = 7700,
    DIVISEUR_VITESSE_ENFANT_MOYENNE = 7000,
    DIVISEUR_VITESSE_ENFANT_PETITE = 6150,
    DIVISEUR_VITESSE_CHAPEAU_X = 3400,
    DIVISEUR_VITESSE_CHAPEAU_Y = 365,
    DIVISEUR_VITESSE_CHAPEAU_REBOND = 394,
    DIVISEUR_VITESSE_MIN_BULLE = 4400,
    DIVISEUR_VITESSE_LACHER_BULLE = DIVISEUR_VITESSE_MIN_BULLE,
    DIVISEUR_VITESSE_LACHER_BULLE_Y = 427,
    DIVISEUR_GRAVITE_CHAPEAU = 17000,
    DIVISEUR_AURA_MARGE = 128
};

enum {
    DIVISEUR_VITESSE_NIVEAU_1 = 8500,
    DIVISEUR_VITESSE_NIVEAU_2 = 7000,
    DIVISEUR_VITESSE_NIVEAU_3_GAUCHE = 7700,
    DIVISEUR_VITESSE_NIVEAU_3_DROITE = 5500,
    DIVISEUR_VITESSE_NIVEAU_3_VIF_DOR = 4800,
    DIVISEUR_VITESSE_NIVEAU_4_GAUCHE = DIVISEUR_VITESSE_NIVEAU_3_DROITE,
    DIVISEUR_VITESSE_NIVEAU_4_CENTRE = 6400,
    DIVISEUR_VITESSE_NIVEAU_4_DROITE = 4400,
    DIVISEUR_VITESSE_NIVEAU_4_VIF_DOR = 4267,
    DIVISEUR_VITESSE_NIVEAU_5 = DIVISEUR_VITESSE_NIVEAU_3_DROITE
};

#define ATTENUATION_TRES_GRANDE 0.995f
#define ATTENUATION_GRANDE 0.992f
#define ATTENUATION_MOYENNE 0.989f
#define ATTENUATION_PETITE 0.985f
#define POSITION_X_NIVEAU_1 0.68f
#define POSITION_Y_NIVEAU_1 0.14f
#define POSITION_X_NIVEAU_2 0.72f
#define POSITION_Y_NIVEAU_2 0.11f
#define POSITION_X_NIVEAU_3_GAUCHE 0.28f
#define POSITION_X_NIVEAU_3_DROITE 0.72f
#define POSITION_X_NIVEAU_3_VIF_DOR 0.48f
#define POSITION_Y_NIVEAU_3_BULLES 0.11f
#define POSITION_Y_NIVEAU_3_VIF_DOR 0.08f
#define POSITION_X_NIVEAU_4_GAUCHE 0.20f
#define POSITION_X_NIVEAU_4_CENTRE 0.52f
#define POSITION_X_NIVEAU_4_DROITE 0.78f
#define POSITION_X_NIVEAU_4_VIF_DOR 0.50f
#define POSITION_Y_NIVEAU_4_HAUT 0.10f
#define POSITION_Y_NIVEAU_4_CENTRE 0.17f
#define POSITION_Y_NIVEAU_4_VIF_DOR 0.07f
#define POSITION_X_NIVEAU_5_BOSS 0.50f
#define POSITION_Y_NIVEAU_5_BOSS 0.10f
#define DECALAGE_SEPARATION_BULLE 0.15f
#define ZERO_FLOTTANT 0.0f

#ifndef JEU_FENETRE_LARGEUR_NUMERATEUR
#define JEU_FENETRE_LARGEUR_NUMERATEUR 4
#endif

#ifndef JEU_FENETRE_HAUTEUR_NUMERATEUR
#define JEU_FENETRE_HAUTEUR_NUMERATEUR 4
#endif

#ifndef JEU_FENETRE_RATIO_DENOMINATEUR
#define JEU_FENETRE_RATIO_DENOMINATEUR 5
#endif

enum {
    COULEUR_CANAL_MIN = VALEUR_NULLE,
    COULEUR_CANAL_MAX = 255,
    COULEUR_NOIR_R = COULEUR_CANAL_MIN,
    COULEUR_NOIR_G = COULEUR_CANAL_MIN,
    COULEUR_NOIR_B = COULEUR_CANAL_MIN,
    COULEUR_BLANC_R = COULEUR_CANAL_MAX,
    COULEUR_BLANC_G = COULEUR_CANAL_MAX,
    COULEUR_BLANC_B = COULEUR_CANAL_MAX,
    COULEUR_MAGENTA_R = COULEUR_CANAL_MAX,
    COULEUR_MAGENTA_G = COULEUR_CANAL_MIN,
    COULEUR_MAGENTA_B = COULEUR_CANAL_MAX,
    COULEUR_SOL_R = 70,
    COULEUR_SOL_G = 120,
    COULEUR_SOL_B = 55,
    COULEUR_BOSS_FOND_R = 55,
    COULEUR_BOSS_FOND_G = COULEUR_CANAL_MIN,
    COULEUR_BOSS_FOND_B = COULEUR_CANAL_MIN,
    COULEUR_BOSS_VIE_R = 220,
    COULEUR_BOSS_VIE_G = COULEUR_CANAL_MIN,
    COULEUR_BOSS_VIE_B = COULEUR_CANAL_MIN
};

enum {
    COULEUR_PANNEAU_MENU_FOND_R = 10,
    COULEUR_PANNEAU_MENU_FOND_G = 10,
    COULEUR_PANNEAU_MENU_FOND_B = 10,
    COULEUR_PANNEAU_MENU_CONTOUR_R = 170,
    COULEUR_PANNEAU_MENU_CONTOUR_G = 170,
    COULEUR_PANNEAU_MENU_CONTOUR_B = 170,
    COULEUR_PANNEAU_MENU_INTERNE_R = 60,
    COULEUR_PANNEAU_MENU_INTERNE_G = 60,
    COULEUR_PANNEAU_MENU_INTERNE_B = 60,
    COULEUR_OPTION_INACTIVE_FOND_R = 18,
    COULEUR_OPTION_INACTIVE_FOND_G = 18,
    COULEUR_OPTION_INACTIVE_FOND_B = 18,
    COULEUR_OPTION_INACTIVE_TEXTE_R = 90,
    COULEUR_OPTION_INACTIVE_TEXTE_G = 90,
    COULEUR_OPTION_INACTIVE_TEXTE_B = 90,
    COULEUR_OPTION_INACTIVE_CADRE_R = 40,
    COULEUR_OPTION_INACTIVE_CADRE_G = 40,
    COULEUR_OPTION_INACTIVE_CADRE_B = 40,
    COULEUR_OPTION_SELECTION_FOND_R = 230,
    COULEUR_OPTION_SELECTION_FOND_G = 230,
    COULEUR_OPTION_SELECTION_FOND_B = 230,
    COULEUR_OPTION_SELECTION_TEXTE_R = 20,
    COULEUR_OPTION_SELECTION_TEXTE_G = 20,
    COULEUR_OPTION_SELECTION_TEXTE_B = 20,
    COULEUR_OPTION_ACTIVE_FOND_R = 24,
    COULEUR_OPTION_ACTIVE_FOND_G = 24,
    COULEUR_OPTION_ACTIVE_FOND_B = 24,
    COULEUR_OPTION_ACTIVE_TEXTE_R = 220,
    COULEUR_OPTION_ACTIVE_TEXTE_G = 220,
    COULEUR_OPTION_ACTIVE_TEXTE_B = 220,
    COULEUR_OPTION_ACTIVE_CADRE_R = 90,
    COULEUR_OPTION_ACTIVE_CADRE_G = 90,
    COULEUR_OPTION_ACTIVE_CADRE_B = 90,
    COULEUR_HUD_FOND_R = 150,
    COULEUR_HUD_FOND_G = 20,
    COULEUR_HUD_FOND_B = 20,
    COULEUR_HUD_CONTOUR_R = COULEUR_CANAL_MAX,
    COULEUR_HUD_CONTOUR_G = 235,
    COULEUR_HUD_CONTOUR_B = 235,
    COULEUR_HUD_CONTOUR_INTERNE_R = 90,
    COULEUR_HUD_CONTOUR_INTERNE_G = COULEUR_CANAL_MIN,
    COULEUR_HUD_CONTOUR_INTERNE_B = COULEUR_CANAL_MIN,
    COULEUR_HUD_TITRE_R = COULEUR_CANAL_MAX,
    COULEUR_HUD_TITRE_G = 245,
    COULEUR_HUD_TITRE_B = 245,
    COULEUR_HUD_AURA_ACTIVE_R = COULEUR_CANAL_MAX,
    COULEUR_HUD_AURA_ACTIVE_G = 240,
    COULEUR_HUD_AURA_ACTIVE_B = 120,
    COULEUR_HUD_AURA_INACTIVE_R = COULEUR_CANAL_MAX,
    COULEUR_HUD_AURA_INACTIVE_G = 220,
    COULEUR_HUD_AURA_INACTIVE_B = 220,
    COULEUR_BOSS_CONTOUR_R = COULEUR_CANAL_MAX,
    COULEUR_BOSS_CONTOUR_G = 210,
    COULEUR_BOSS_CONTOUR_B = 210,
    COULEUR_TEXTE_AIDE_R = 150,
    COULEUR_TEXTE_AIDE_G = 150,
    COULEUR_TEXTE_AIDE_B = 150,
    COULEUR_TEXTE_SAUVEGARDE_R = 120,
    COULEUR_TEXTE_SAUVEGARDE_G = 120,
    COULEUR_TEXTE_SAUVEGARDE_B = 120,
    COULEUR_TEXTE_INSTRUCTION_R = 140,
    COULEUR_TEXTE_INSTRUCTION_G = 140,
    COULEUR_TEXTE_INSTRUCTION_B = 140,
    COULEUR_TEXTE_INFO_R = 210,
    COULEUR_TEXTE_INFO_G = 210,
    COULEUR_TEXTE_INFO_B = 210,
    COULEUR_TEXTE_SAISIE_R = 200,
    COULEUR_TEXTE_SAISIE_G = 200,
    COULEUR_TEXTE_SAISIE_B = 200,
    COULEUR_ROUGE_R = COULEUR_CANAL_MAX,
    COULEUR_ROUGE_G = COULEUR_CANAL_MIN,
    COULEUR_ROUGE_B = COULEUR_CANAL_MIN,
    COULEUR_VERT_R = COULEUR_CANAL_MIN,
    COULEUR_VERT_G = COULEUR_CANAL_MAX,
    COULEUR_VERT_B = COULEUR_CANAL_MIN,
    TAILLE_CHEMIN_RESSOURCE = 512,
    TAILLE_LIGNE_HUD = 128,
    TAILLE_TEXTE_MENU = 64,
    TAILLE_TEXTE_DECOMPTE = 8
};

#define FORMAT_CHRONOMETRE_HUD "Temps : %03d s"
#define FORMAT_AURA_ARDENTE_HUD "Aura ardente : %.1f s"
#define FORMAT_CHEMIN_SAUVEGARDE_SLOT "savegame_%d.dat"
#define CHEMIN_FOND_NIVEAU_2 "assets/room_24bit.bmp"
#define CHEMIN_FOND_NIVEAU_3 "assets/library_24bit.bmp"
#define CHEMIN_FOND_NIVEAU_4 "assets/hall_24bit.bmp"
#define CHEMIN_FOND_NIVEAU_5 "assets/duel_24bit.bmp"
#define CHEMIN_SPRITE_VOL_DE_MORT "assets/vol_de_mort.bmp"
#define PREFIXE_RESSOURCE_PROJET "01_projet_jeu/"
#define PREFIXE_RESSOURCE_PARENT_PROJET "../01_projet_jeu/"

static inline int dimension_relative(int reference, int diviseur) {
    int valeur;

    if (reference <= VALEUR_NULLE || diviseur <= VALEUR_NULLE) {
        return VALEUR_NULLE;
    }

    valeur = reference / diviseur;
    if (valeur <= VALEUR_NULLE) {
        valeur = reference / reference;
    }

    return valeur;
}

enum {
    CODE_BITS_TOUCHE = 8,
    MASQUE_ASCII_TOUCHE = 0xff,
    CARACTERE_CHIFFRE_MIN = '0',
    CARACTERE_CHIFFRE_MAX = '9'
};

#endif
